### PR TITLE
removes words that may be inappropriate; also removes duplicates

### PR DESCRIPTION
**Pull request by ifrim**
## Notes
For the nouns list there are a few duplicates and most of them are inappropriate words, more or less. Some of them may seem innocent (e.g. "ball" or "bottom") but they can lead to inappropriate meanings in combination with a lot of adjectives.

For the adjectives list it is the other way around. There are a few ones that I took out like "dirty" of "filthy" because they make everything sound dirty or filthy :)
But the majority of them (~98-99%) are just duplicates.

I may have exaggerated with some words. If so just let me know and I'll put them back in.

addresses https://github.com/TykTechnologies/ara/issues/460

### CODE REVIEW

**Comment by excieve** [comment]
@ifrim Do you know how many possible adjective-noun permutations would there be after this change?

**Comment by ifrim** [comment]
> @ifrim Do you know how many possible adjective-noun permutations would there be after this change?

If this PR will be accepted as is there will be 1213 adjectives and 4514 nouns. And unless we can have the order in reverse (<noun>-<adjective>) there should be 1213 * 4514 unique pairs, which is 5475482.

**Review by excieve — APPROVED** [review]
Thanks a lot for doing this @ifrim! If there are any stragglers this can be revisited.

**Comment by excieve** [comment]
Now to find whoever can merge this :D

**Pull request merged**
